// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdf2xvqFYFxfwgOUULS7FVsggEFT95-y8',
    appId: '1:240938014180:web:639812f6d710e55f4623f1',
    messagingSenderId: '240938014180',
    projectId: 'catalogak-3f7c0',
    authDomain: 'catalogak-3f7c0.firebaseapp.com',
    storageBucket: 'catalogak-3f7c0.appspot.com',
    measurementId: 'G-BRR590XF6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Htn4cKG7Wc7No5CWkfzA3offCEega9I',
    appId: '1:240938014180:android:01d3d4e4aa8da6664623f1',
    messagingSenderId: '240938014180',
    projectId: 'catalogak-3f7c0',
    storageBucket: 'catalogak-3f7c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyvHCigR1WyjIkhh_i03B0bm_YOVfCMQ4',
    appId: '1:240938014180:ios:dc9b734418cef80c4623f1',
    messagingSenderId: '240938014180',
    projectId: 'catalogak-3f7c0',
    storageBucket: 'catalogak-3f7c0.appspot.com',
    iosBundleId: 'ae.altkamul.iclient',
  );
}
