// Mocks generated by Mockito 5.4.4 from annotations
// in merchant_dashboard/test/helpers/test_mockes.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:dio/dio.dart' as _i9;
import 'package:merchant_dashboard/feature/auth/data/data_sources/login_local_datasource.dart'
    as _i16;
import 'package:merchant_dashboard/feature/auth/data/data_sources/login_remote_datasource.dart'
    as _i10;
import 'package:merchant_dashboard/feature/auth/data/models/params/login_request_parameter.dart'
    as _i12;
import 'package:merchant_dashboard/feature/auth/data/models/params/register_request_parameter.dart'
    as _i13;
import 'package:merchant_dashboard/feature/auth/data/models/params/reset_password_parameter.dart'
    as _i15;
import 'package:merchant_dashboard/feature/auth/data/models/responses/login_response.dart'
    as _i2;
import 'package:merchant_dashboard/feature/dashboard/data/data_source/dashboard_remote_datasource.dart'
    as _i17;
import 'package:merchant_dashboard/feature/dashboard/data/models/params/dashboard_data_parameter.dart'
    as _i19;
import 'package:merchant_dashboard/feature/dashboard/data/models/responses/orders_statistics/orders_statistics_response.dart'
    as _i4;
import 'package:merchant_dashboard/feature/dashboard/data/models/responses/reports/report_response.dart'
    as _i6;
import 'package:merchant_dashboard/feature/dashboard/data/models/responses/sales/sales_per_timeline_response.dart'
    as _i18;
import 'package:merchant_dashboard/feature/dashboard/data/models/responses/sales/sales_statistics_response.dart'
    as _i3;
import 'package:merchant_dashboard/feature/dashboard/data/models/responses/top_items/top_sales_data_response.dart'
    as _i5;
import 'package:merchant_dashboard/feature/dashboard/data/models/responses/top_sub_categories/top_sub_categories_item_response.dart'
    as _i7;
import 'package:merchant_dashboard/feature/dashboard/data/models/responses/worker/worker_sales_response.dart'
    as _i8;
import 'package:merchant_dashboard/feature/orders/data/models/response/top_last/top_last_orders_response.dart'
    as _i20;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponse_0 extends _i1.SmartFake implements _i2.LoginResponse {
  _FakeLoginResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSalesStatisticsResponse_1 extends _i1.SmartFake
    implements _i3.SalesStatisticsResponse {
  _FakeSalesStatisticsResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrdersStatisticsResponse_2 extends _i1.SmartFake
    implements _i4.OrdersStatisticsResponse {
  _FakeOrdersStatisticsResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTopSalesResponse_3 extends _i1.SmartFake
    implements _i5.TopSalesResponse {
  _FakeTopSalesResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReportsResponse_4 extends _i1.SmartFake
    implements _i6.ReportsResponse {
  _FakeReportsResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTopSubCategoriesResponse_5 extends _i1.SmartFake
    implements _i7.TopSubCategoriesResponse {
  _FakeTopSubCategoriesResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkerSalesResponse_6 extends _i1.SmartFake
    implements _i8.WorkerSalesResponse {
  _FakeWorkerSalesResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseOptions_7 extends _i1.SmartFake implements _i9.BaseOptions {
  _FakeBaseOptions_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientAdapter_8 extends _i1.SmartFake
    implements _i9.HttpClientAdapter {
  _FakeHttpClientAdapter_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransformer_9 extends _i1.SmartFake implements _i9.Transformer {
  _FakeTransformer_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterceptors_10 extends _i1.SmartFake implements _i9.Interceptors {
  _FakeInterceptors_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_11<T1> extends _i1.SmartFake implements _i9.Response<T1> {
  _FakeResponse_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ILoginRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockILoginRemoteDataSource extends _i1.Mock
    implements _i10.ILoginRemoteDataSource {
  @override
  _i11.Future<_i2.LoginResponse> loginRequest(
          _i12.LoginRequestParameter? loginRequestParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginRequest,
          [loginRequestParameter],
        ),
        returnValue: _i11.Future<_i2.LoginResponse>.value(_FakeLoginResponse_0(
          this,
          Invocation.method(
            #loginRequest,
            [loginRequestParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i2.LoginResponse>.value(_FakeLoginResponse_0(
          this,
          Invocation.method(
            #loginRequest,
            [loginRequestParameter],
          ),
        )),
      ) as _i11.Future<_i2.LoginResponse>);

  @override
  _i11.Future<({String password, String userId})> registerMobile(
          _i13.RegisterRequestParameter? parameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerMobile,
          [parameter],
        ),
        returnValue: _i11.Future<({String password, String userId})>.value((
          password: _i14.dummyValue<String>(
            this,
            Invocation.method(
              #registerMobile,
              [parameter],
            ),
          ),
          userId: _i14.dummyValue<String>(
            this,
            Invocation.method(
              #registerMobile,
              [parameter],
            ),
          )
        )),
        returnValueForMissingStub:
            _i11.Future<({String password, String userId})>.value((
          password: _i14.dummyValue<String>(
            this,
            Invocation.method(
              #registerMobile,
              [parameter],
            ),
          ),
          userId: _i14.dummyValue<String>(
            this,
            Invocation.method(
              #registerMobile,
              [parameter],
            ),
          )
        )),
      ) as _i11.Future<({String password, String userId})>);

  @override
  _i11.Future<bool> registerEmail(_i13.RegisterRequestParameter? parameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerEmail,
          [parameter],
        ),
        returnValue: _i11.Future<bool>.value(false),
        returnValueForMissingStub: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<bool> forgetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [email],
        ),
        returnValue: _i11.Future<bool>.value(false),
        returnValueForMissingStub: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<bool> resetPassword(_i15.ResetPasswordParameter? parameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [parameter],
        ),
        returnValue: _i11.Future<bool>.value(false),
        returnValueForMissingStub: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);
}

/// A class which mocks [ILoginLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockILoginLocalDataSource extends _i1.Mock
    implements _i16.ILoginLocalDataSource {
  @override
  void saveUserInfo({
    required String? userToken,
    required String? userRefreshToken,
    required String? userName,
    required String? merchantName,
    required String? userId,
    required String? branchName,
    required String? userLevel,
    required String? businessId,
    required String? phoneNumber,
    required String? branchEmail,
    required bool? hasBranch,
    required String? registeredDate,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #saveUserInfo,
          [],
          {
            #userToken: userToken,
            #userRefreshToken: userRefreshToken,
            #userName: userName,
            #merchantName: merchantName,
            #userId: userId,
            #branchName: branchName,
            #userLevel: userLevel,
            #businessId: businessId,
            #phoneNumber: phoneNumber,
            #branchEmail: branchEmail,
            #hasBranch: hasBranch,
            #registeredDate: registeredDate,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateUserTokens({
    required String? token,
    required String? refreshToken,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateUserTokens,
          [],
          {
            #token: token,
            #refreshToken: refreshToken,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logoutUser() => super.noSuchMethod(
        Invocation.method(
          #logoutUser,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getSelectedMerchantId() => (super.noSuchMethod(
        Invocation.method(
          #getSelectedMerchantId,
          [],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getSelectedMerchantId,
            [],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getSelectedMerchantId,
            [],
          ),
        ),
      ) as String);

  @override
  String getUserLevel() => (super.noSuchMethod(
        Invocation.method(
          #getUserLevel,
          [],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getUserLevel,
            [],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getUserLevel,
            [],
          ),
        ),
      ) as String);

  @override
  String getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getUserId,
            [],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getUserId,
            [],
          ),
        ),
      ) as String);

  @override
  String getBusinessId() => (super.noSuchMethod(
        Invocation.method(
          #getBusinessId,
          [],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getBusinessId,
            [],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getBusinessId,
            [],
          ),
        ),
      ) as String);

  @override
  String getUserMerchantName() => (super.noSuchMethod(
        Invocation.method(
          #getUserMerchantName,
          [],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getUserMerchantName,
            [],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getUserMerchantName,
            [],
          ),
        ),
      ) as String);

  @override
  String getLoggedInUserPhoneNumber() => (super.noSuchMethod(
        Invocation.method(
          #getLoggedInUserPhoneNumber,
          [],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getLoggedInUserPhoneNumber,
            [],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getLoggedInUserPhoneNumber,
            [],
          ),
        ),
      ) as String);

  @override
  String getUserName() => (super.noSuchMethod(
        Invocation.method(
          #getUserName,
          [],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getUserName,
            [],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getUserName,
            [],
          ),
        ),
      ) as String);

  @override
  String getLoggedInUserEmail() => (super.noSuchMethod(
        Invocation.method(
          #getLoggedInUserEmail,
          [],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getLoggedInUserEmail,
            [],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getLoggedInUserEmail,
            [],
          ),
        ),
      ) as String);

  @override
  String getUserRegisteredDate() => (super.noSuchMethod(
        Invocation.method(
          #getUserRegisteredDate,
          [],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getUserRegisteredDate,
            [],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getUserRegisteredDate,
            [],
          ),
        ),
      ) as String);

  @override
  void setSelectedMerchantId({required String? merchantId}) =>
      super.noSuchMethod(
        Invocation.method(
          #setSelectedMerchantId,
          [],
          {#merchantId: merchantId},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isLoggedInUserBusiness() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedInUserBusiness,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String getBranchName() => (super.noSuchMethod(
        Invocation.method(
          #getBranchName,
          [],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getBranchName,
            [],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getBranchName,
            [],
          ),
        ),
      ) as String);

  @override
  bool hasBranch() => (super.noSuchMethod(
        Invocation.method(
          #hasBranch,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void saveHasBranch(bool? hasBranch) => super.noSuchMethod(
        Invocation.method(
          #saveHasBranch,
          [hasBranch],
        ),
        returnValueForMissingStub: null,
      );

  @override
  ({
    String branchName,
    String businessId,
    String merchantName,
    String userId,
    String userLevel,
    String userName
  }) getLoggedInUserInfo() => (super.noSuchMethod(
        Invocation.method(
          #getLoggedInUserInfo,
          [],
        ),
        returnValue: (
          branchName: _i14.dummyValue<String>(
            this,
            Invocation.method(
              #getLoggedInUserInfo,
              [],
            ),
          ),
          businessId: _i14.dummyValue<String>(
            this,
            Invocation.method(
              #getLoggedInUserInfo,
              [],
            ),
          ),
          merchantName: _i14.dummyValue<String>(
            this,
            Invocation.method(
              #getLoggedInUserInfo,
              [],
            ),
          ),
          userId: _i14.dummyValue<String>(
            this,
            Invocation.method(
              #getLoggedInUserInfo,
              [],
            ),
          ),
          userLevel: _i14.dummyValue<String>(
            this,
            Invocation.method(
              #getLoggedInUserInfo,
              [],
            ),
          ),
          userName: _i14.dummyValue<String>(
            this,
            Invocation.method(
              #getLoggedInUserInfo,
              [],
            ),
          )
        ),
        returnValueForMissingStub: (
          branchName: _i14.dummyValue<String>(
            this,
            Invocation.method(
              #getLoggedInUserInfo,
              [],
            ),
          ),
          businessId: _i14.dummyValue<String>(
            this,
            Invocation.method(
              #getLoggedInUserInfo,
              [],
            ),
          ),
          merchantName: _i14.dummyValue<String>(
            this,
            Invocation.method(
              #getLoggedInUserInfo,
              [],
            ),
          ),
          userId: _i14.dummyValue<String>(
            this,
            Invocation.method(
              #getLoggedInUserInfo,
              [],
            ),
          ),
          userLevel: _i14.dummyValue<String>(
            this,
            Invocation.method(
              #getLoggedInUserInfo,
              [],
            ),
          ),
          userName: _i14.dummyValue<String>(
            this,
            Invocation.method(
              #getLoggedInUserInfo,
              [],
            ),
          )
        ),
      ) as ({
        String branchName,
        String businessId,
        String merchantName,
        String userId,
        String userLevel,
        String userName
      }));
}

/// A class which mocks [IDashboardRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDashboardRemoteDataSource extends _i1.Mock
    implements _i17.IDashboardRemoteDataSource {
  @override
  _i11.Future<_i18.SalesPerTimelineResponse?> getSalesPerToday(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSalesPerToday,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i18.SalesPerTimelineResponse?>.value(),
        returnValueForMissingStub:
            _i11.Future<_i18.SalesPerTimelineResponse?>.value(),
      ) as _i11.Future<_i18.SalesPerTimelineResponse?>);

  @override
  _i11.Future<_i18.SalesPerTimelineResponse?> getSalesPerWeek(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSalesPerWeek,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i18.SalesPerTimelineResponse?>.value(),
        returnValueForMissingStub:
            _i11.Future<_i18.SalesPerTimelineResponse?>.value(),
      ) as _i11.Future<_i18.SalesPerTimelineResponse?>);

  @override
  _i11.Future<_i18.SalesPerTimelineResponse?> getSalesPerMonth(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSalesPerMonth,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i18.SalesPerTimelineResponse?>.value(),
        returnValueForMissingStub:
            _i11.Future<_i18.SalesPerTimelineResponse?>.value(),
      ) as _i11.Future<_i18.SalesPerTimelineResponse?>);

  @override
  _i11.Future<_i18.SalesPerTimelineResponse?> getSalesPerDate(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSalesPerDate,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i18.SalesPerTimelineResponse?>.value(),
        returnValueForMissingStub:
            _i11.Future<_i18.SalesPerTimelineResponse?>.value(),
      ) as _i11.Future<_i18.SalesPerTimelineResponse?>);

  @override
  _i11.Future<_i18.SalesPerTimelineResponse?> getOrdersPerToday(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrdersPerToday,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i18.SalesPerTimelineResponse?>.value(),
        returnValueForMissingStub:
            _i11.Future<_i18.SalesPerTimelineResponse?>.value(),
      ) as _i11.Future<_i18.SalesPerTimelineResponse?>);

  @override
  _i11.Future<_i18.SalesPerTimelineResponse?> getOrdersPerWeek(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrdersPerWeek,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i18.SalesPerTimelineResponse?>.value(),
        returnValueForMissingStub:
            _i11.Future<_i18.SalesPerTimelineResponse?>.value(),
      ) as _i11.Future<_i18.SalesPerTimelineResponse?>);

  @override
  _i11.Future<_i18.SalesPerTimelineResponse?> getOrdersPerMonth(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrdersPerMonth,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i18.SalesPerTimelineResponse?>.value(),
        returnValueForMissingStub:
            _i11.Future<_i18.SalesPerTimelineResponse?>.value(),
      ) as _i11.Future<_i18.SalesPerTimelineResponse?>);

  @override
  _i11.Future<_i18.SalesPerTimelineResponse?> getOrdersPerDate(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrdersPerDate,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i18.SalesPerTimelineResponse?>.value(),
        returnValueForMissingStub:
            _i11.Future<_i18.SalesPerTimelineResponse?>.value(),
      ) as _i11.Future<_i18.SalesPerTimelineResponse?>);

  @override
  _i11.Future<_i3.SalesStatisticsResponse> getSalesStatisticsPerToday(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSalesStatisticsPerToday,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i3.SalesStatisticsResponse>.value(
            _FakeSalesStatisticsResponse_1(
          this,
          Invocation.method(
            #getSalesStatisticsPerToday,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i3.SalesStatisticsResponse>.value(
                _FakeSalesStatisticsResponse_1(
          this,
          Invocation.method(
            #getSalesStatisticsPerToday,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i3.SalesStatisticsResponse>);

  @override
  _i11.Future<_i3.SalesStatisticsResponse> getSalesStatisticsPerWeek(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSalesStatisticsPerWeek,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i3.SalesStatisticsResponse>.value(
            _FakeSalesStatisticsResponse_1(
          this,
          Invocation.method(
            #getSalesStatisticsPerWeek,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i3.SalesStatisticsResponse>.value(
                _FakeSalesStatisticsResponse_1(
          this,
          Invocation.method(
            #getSalesStatisticsPerWeek,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i3.SalesStatisticsResponse>);

  @override
  _i11.Future<_i3.SalesStatisticsResponse> getSalesStatisticsPerMonth(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSalesStatisticsPerMonth,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i3.SalesStatisticsResponse>.value(
            _FakeSalesStatisticsResponse_1(
          this,
          Invocation.method(
            #getSalesStatisticsPerMonth,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i3.SalesStatisticsResponse>.value(
                _FakeSalesStatisticsResponse_1(
          this,
          Invocation.method(
            #getSalesStatisticsPerMonth,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i3.SalesStatisticsResponse>);

  @override
  _i11.Future<_i3.SalesStatisticsResponse> getSalesStatisticsPerDate(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSalesStatisticsPerDate,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i3.SalesStatisticsResponse>.value(
            _FakeSalesStatisticsResponse_1(
          this,
          Invocation.method(
            #getSalesStatisticsPerDate,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i3.SalesStatisticsResponse>.value(
                _FakeSalesStatisticsResponse_1(
          this,
          Invocation.method(
            #getSalesStatisticsPerDate,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i3.SalesStatisticsResponse>);

  @override
  _i11.Future<_i4.OrdersStatisticsResponse> getOrdersStatisticsPerToday(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrdersStatisticsPerToday,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i4.OrdersStatisticsResponse>.value(
            _FakeOrdersStatisticsResponse_2(
          this,
          Invocation.method(
            #getOrdersStatisticsPerToday,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i4.OrdersStatisticsResponse>.value(
                _FakeOrdersStatisticsResponse_2(
          this,
          Invocation.method(
            #getOrdersStatisticsPerToday,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i4.OrdersStatisticsResponse>);

  @override
  _i11.Future<_i4.OrdersStatisticsResponse> getOrdersStatisticsPerWeek(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrdersStatisticsPerWeek,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i4.OrdersStatisticsResponse>.value(
            _FakeOrdersStatisticsResponse_2(
          this,
          Invocation.method(
            #getOrdersStatisticsPerWeek,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i4.OrdersStatisticsResponse>.value(
                _FakeOrdersStatisticsResponse_2(
          this,
          Invocation.method(
            #getOrdersStatisticsPerWeek,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i4.OrdersStatisticsResponse>);

  @override
  _i11.Future<_i4.OrdersStatisticsResponse> getOrdersStatisticsPerMonth(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrdersStatisticsPerMonth,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i4.OrdersStatisticsResponse>.value(
            _FakeOrdersStatisticsResponse_2(
          this,
          Invocation.method(
            #getOrdersStatisticsPerMonth,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i4.OrdersStatisticsResponse>.value(
                _FakeOrdersStatisticsResponse_2(
          this,
          Invocation.method(
            #getOrdersStatisticsPerMonth,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i4.OrdersStatisticsResponse>);

  @override
  _i11.Future<_i4.OrdersStatisticsResponse> getOrdersStatisticsPerDate(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrdersStatisticsPerDate,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i4.OrdersStatisticsResponse>.value(
            _FakeOrdersStatisticsResponse_2(
          this,
          Invocation.method(
            #getOrdersStatisticsPerDate,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i4.OrdersStatisticsResponse>.value(
                _FakeOrdersStatisticsResponse_2(
          this,
          Invocation.method(
            #getOrdersStatisticsPerDate,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i4.OrdersStatisticsResponse>);

  @override
  _i11.Future<_i5.TopSalesResponse> getTopSalesPerToday(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopSalesPerToday,
          [dashboardParameter],
        ),
        returnValue:
            _i11.Future<_i5.TopSalesResponse>.value(_FakeTopSalesResponse_3(
          this,
          Invocation.method(
            #getTopSalesPerToday,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i5.TopSalesResponse>.value(_FakeTopSalesResponse_3(
          this,
          Invocation.method(
            #getTopSalesPerToday,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i5.TopSalesResponse>);

  @override
  _i11.Future<_i5.TopSalesResponse> getTopOrderSalesPerToday(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopOrderSalesPerToday,
          [dashboardParameter],
        ),
        returnValue:
            _i11.Future<_i5.TopSalesResponse>.value(_FakeTopSalesResponse_3(
          this,
          Invocation.method(
            #getTopOrderSalesPerToday,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i5.TopSalesResponse>.value(_FakeTopSalesResponse_3(
          this,
          Invocation.method(
            #getTopOrderSalesPerToday,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i5.TopSalesResponse>);

  @override
  _i11.Future<_i5.TopSalesResponse> getTopSalesPerWeek(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopSalesPerWeek,
          [dashboardParameter],
        ),
        returnValue:
            _i11.Future<_i5.TopSalesResponse>.value(_FakeTopSalesResponse_3(
          this,
          Invocation.method(
            #getTopSalesPerWeek,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i5.TopSalesResponse>.value(_FakeTopSalesResponse_3(
          this,
          Invocation.method(
            #getTopSalesPerWeek,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i5.TopSalesResponse>);

  @override
  _i11.Future<_i5.TopSalesResponse> getTopOrderSalesPerWeek(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopOrderSalesPerWeek,
          [dashboardParameter],
        ),
        returnValue:
            _i11.Future<_i5.TopSalesResponse>.value(_FakeTopSalesResponse_3(
          this,
          Invocation.method(
            #getTopOrderSalesPerWeek,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i5.TopSalesResponse>.value(_FakeTopSalesResponse_3(
          this,
          Invocation.method(
            #getTopOrderSalesPerWeek,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i5.TopSalesResponse>);

  @override
  _i11.Future<_i5.TopSalesResponse> getTopSalesPerMonth(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopSalesPerMonth,
          [dashboardParameter],
        ),
        returnValue:
            _i11.Future<_i5.TopSalesResponse>.value(_FakeTopSalesResponse_3(
          this,
          Invocation.method(
            #getTopSalesPerMonth,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i5.TopSalesResponse>.value(_FakeTopSalesResponse_3(
          this,
          Invocation.method(
            #getTopSalesPerMonth,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i5.TopSalesResponse>);

  @override
  _i11.Future<_i5.TopSalesResponse> getTopOrderSalesPerMonth(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopOrderSalesPerMonth,
          [dashboardParameter],
        ),
        returnValue:
            _i11.Future<_i5.TopSalesResponse>.value(_FakeTopSalesResponse_3(
          this,
          Invocation.method(
            #getTopOrderSalesPerMonth,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i5.TopSalesResponse>.value(_FakeTopSalesResponse_3(
          this,
          Invocation.method(
            #getTopOrderSalesPerMonth,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i5.TopSalesResponse>);

  @override
  _i11.Future<_i5.TopSalesResponse> getTopSalesPerDate(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopSalesPerDate,
          [dashboardParameter],
        ),
        returnValue:
            _i11.Future<_i5.TopSalesResponse>.value(_FakeTopSalesResponse_3(
          this,
          Invocation.method(
            #getTopSalesPerDate,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i5.TopSalesResponse>.value(_FakeTopSalesResponse_3(
          this,
          Invocation.method(
            #getTopSalesPerDate,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i5.TopSalesResponse>);

  @override
  _i11.Future<_i5.TopSalesResponse> getTopOrderSalesPerDateRange(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopOrderSalesPerDateRange,
          [dashboardParameter],
        ),
        returnValue:
            _i11.Future<_i5.TopSalesResponse>.value(_FakeTopSalesResponse_3(
          this,
          Invocation.method(
            #getTopOrderSalesPerDateRange,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i5.TopSalesResponse>.value(_FakeTopSalesResponse_3(
          this,
          Invocation.method(
            #getTopOrderSalesPerDateRange,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i5.TopSalesResponse>);

  @override
  _i11.Future<_i6.ReportsResponse> getReportsPerToday(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReportsPerToday,
          [dashboardParameter],
        ),
        returnValue:
            _i11.Future<_i6.ReportsResponse>.value(_FakeReportsResponse_4(
          this,
          Invocation.method(
            #getReportsPerToday,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i6.ReportsResponse>.value(_FakeReportsResponse_4(
          this,
          Invocation.method(
            #getReportsPerToday,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i6.ReportsResponse>);

  @override
  _i11.Future<_i6.ReportsResponse> getReportsPerWeek(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReportsPerWeek,
          [dashboardParameter],
        ),
        returnValue:
            _i11.Future<_i6.ReportsResponse>.value(_FakeReportsResponse_4(
          this,
          Invocation.method(
            #getReportsPerWeek,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i6.ReportsResponse>.value(_FakeReportsResponse_4(
          this,
          Invocation.method(
            #getReportsPerWeek,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i6.ReportsResponse>);

  @override
  _i11.Future<_i6.ReportsResponse> getReportsPerMonth(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReportsPerMonth,
          [dashboardParameter],
        ),
        returnValue:
            _i11.Future<_i6.ReportsResponse>.value(_FakeReportsResponse_4(
          this,
          Invocation.method(
            #getReportsPerMonth,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i6.ReportsResponse>.value(_FakeReportsResponse_4(
          this,
          Invocation.method(
            #getReportsPerMonth,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i6.ReportsResponse>);

  @override
  _i11.Future<_i6.ReportsResponse> getReportsPerDate(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReportsPerDate,
          [dashboardParameter],
        ),
        returnValue:
            _i11.Future<_i6.ReportsResponse>.value(_FakeReportsResponse_4(
          this,
          Invocation.method(
            #getReportsPerDate,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i6.ReportsResponse>.value(_FakeReportsResponse_4(
          this,
          Invocation.method(
            #getReportsPerDate,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i6.ReportsResponse>);

  @override
  _i11.Future<_i7.TopSubCategoriesResponse> getTopSubCategoriesPerToday(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopSubCategoriesPerToday,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i7.TopSubCategoriesResponse>.value(
            _FakeTopSubCategoriesResponse_5(
          this,
          Invocation.method(
            #getTopSubCategoriesPerToday,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i7.TopSubCategoriesResponse>.value(
                _FakeTopSubCategoriesResponse_5(
          this,
          Invocation.method(
            #getTopSubCategoriesPerToday,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i7.TopSubCategoriesResponse>);

  @override
  _i11.Future<_i7.TopSubCategoriesResponse> getTopOrderSubCategoriesPerToday(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopOrderSubCategoriesPerToday,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i7.TopSubCategoriesResponse>.value(
            _FakeTopSubCategoriesResponse_5(
          this,
          Invocation.method(
            #getTopOrderSubCategoriesPerToday,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i7.TopSubCategoriesResponse>.value(
                _FakeTopSubCategoriesResponse_5(
          this,
          Invocation.method(
            #getTopOrderSubCategoriesPerToday,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i7.TopSubCategoriesResponse>);

  @override
  _i11.Future<_i7.TopSubCategoriesResponse> getTopSubCategoriesPerWeek(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopSubCategoriesPerWeek,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i7.TopSubCategoriesResponse>.value(
            _FakeTopSubCategoriesResponse_5(
          this,
          Invocation.method(
            #getTopSubCategoriesPerWeek,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i7.TopSubCategoriesResponse>.value(
                _FakeTopSubCategoriesResponse_5(
          this,
          Invocation.method(
            #getTopSubCategoriesPerWeek,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i7.TopSubCategoriesResponse>);

  @override
  _i11.Future<_i7.TopSubCategoriesResponse> getTopOrderSubCategoriesPerWeek(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopOrderSubCategoriesPerWeek,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i7.TopSubCategoriesResponse>.value(
            _FakeTopSubCategoriesResponse_5(
          this,
          Invocation.method(
            #getTopOrderSubCategoriesPerWeek,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i7.TopSubCategoriesResponse>.value(
                _FakeTopSubCategoriesResponse_5(
          this,
          Invocation.method(
            #getTopOrderSubCategoriesPerWeek,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i7.TopSubCategoriesResponse>);

  @override
  _i11.Future<_i7.TopSubCategoriesResponse> getTopSubCategoriesPerMonth(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopSubCategoriesPerMonth,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i7.TopSubCategoriesResponse>.value(
            _FakeTopSubCategoriesResponse_5(
          this,
          Invocation.method(
            #getTopSubCategoriesPerMonth,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i7.TopSubCategoriesResponse>.value(
                _FakeTopSubCategoriesResponse_5(
          this,
          Invocation.method(
            #getTopSubCategoriesPerMonth,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i7.TopSubCategoriesResponse>);

  @override
  _i11.Future<_i7.TopSubCategoriesResponse> getTopOrderSubCategoriesPerMonth(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopOrderSubCategoriesPerMonth,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i7.TopSubCategoriesResponse>.value(
            _FakeTopSubCategoriesResponse_5(
          this,
          Invocation.method(
            #getTopOrderSubCategoriesPerMonth,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i7.TopSubCategoriesResponse>.value(
                _FakeTopSubCategoriesResponse_5(
          this,
          Invocation.method(
            #getTopOrderSubCategoriesPerMonth,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i7.TopSubCategoriesResponse>);

  @override
  _i11.Future<_i7.TopSubCategoriesResponse> getTopSubCategoriesPerDate(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopSubCategoriesPerDate,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i7.TopSubCategoriesResponse>.value(
            _FakeTopSubCategoriesResponse_5(
          this,
          Invocation.method(
            #getTopSubCategoriesPerDate,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i7.TopSubCategoriesResponse>.value(
                _FakeTopSubCategoriesResponse_5(
          this,
          Invocation.method(
            #getTopSubCategoriesPerDate,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i7.TopSubCategoriesResponse>);

  @override
  _i11.Future<_i7.TopSubCategoriesResponse> getTopOrderSubCategoriesPerDate(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopOrderSubCategoriesPerDate,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i7.TopSubCategoriesResponse>.value(
            _FakeTopSubCategoriesResponse_5(
          this,
          Invocation.method(
            #getTopOrderSubCategoriesPerDate,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i7.TopSubCategoriesResponse>.value(
                _FakeTopSubCategoriesResponse_5(
          this,
          Invocation.method(
            #getTopOrderSubCategoriesPerDate,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i7.TopSubCategoriesResponse>);

  @override
  _i11.Future<_i8.WorkerSalesResponse> getWorkerSalesPerToday(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkerSalesPerToday,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i8.WorkerSalesResponse>.value(
            _FakeWorkerSalesResponse_6(
          this,
          Invocation.method(
            #getWorkerSalesPerToday,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub: _i11.Future<_i8.WorkerSalesResponse>.value(
            _FakeWorkerSalesResponse_6(
          this,
          Invocation.method(
            #getWorkerSalesPerToday,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i8.WorkerSalesResponse>);

  @override
  _i11.Future<_i8.WorkerSalesResponse> getWorkerSalesPerWeek(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkerSalesPerWeek,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i8.WorkerSalesResponse>.value(
            _FakeWorkerSalesResponse_6(
          this,
          Invocation.method(
            #getWorkerSalesPerWeek,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub: _i11.Future<_i8.WorkerSalesResponse>.value(
            _FakeWorkerSalesResponse_6(
          this,
          Invocation.method(
            #getWorkerSalesPerWeek,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i8.WorkerSalesResponse>);

  @override
  _i11.Future<_i8.WorkerSalesResponse> getWorkerSalesPerMonth(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkerSalesPerMonth,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i8.WorkerSalesResponse>.value(
            _FakeWorkerSalesResponse_6(
          this,
          Invocation.method(
            #getWorkerSalesPerMonth,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub: _i11.Future<_i8.WorkerSalesResponse>.value(
            _FakeWorkerSalesResponse_6(
          this,
          Invocation.method(
            #getWorkerSalesPerMonth,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i8.WorkerSalesResponse>);

  @override
  _i11.Future<_i8.WorkerSalesResponse> getWorkerSalesPerDateRange(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkerSalesPerDateRange,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<_i8.WorkerSalesResponse>.value(
            _FakeWorkerSalesResponse_6(
          this,
          Invocation.method(
            #getWorkerSalesPerDateRange,
            [dashboardParameter],
          ),
        )),
        returnValueForMissingStub: _i11.Future<_i8.WorkerSalesResponse>.value(
            _FakeWorkerSalesResponse_6(
          this,
          Invocation.method(
            #getWorkerSalesPerDateRange,
            [dashboardParameter],
          ),
        )),
      ) as _i11.Future<_i8.WorkerSalesResponse>);

  @override
  _i11.Future<List<_i20.TopLastOrdersResponse>> getTransactionOrdersPerToday(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionOrdersPerToday,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<List<_i20.TopLastOrdersResponse>>.value(
            <_i20.TopLastOrdersResponse>[]),
        returnValueForMissingStub:
            _i11.Future<List<_i20.TopLastOrdersResponse>>.value(
                <_i20.TopLastOrdersResponse>[]),
      ) as _i11.Future<List<_i20.TopLastOrdersResponse>>);

  @override
  _i11.Future<List<_i20.TopLastOrdersResponse>> getTransactionOrdersPerWeek(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionOrdersPerWeek,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<List<_i20.TopLastOrdersResponse>>.value(
            <_i20.TopLastOrdersResponse>[]),
        returnValueForMissingStub:
            _i11.Future<List<_i20.TopLastOrdersResponse>>.value(
                <_i20.TopLastOrdersResponse>[]),
      ) as _i11.Future<List<_i20.TopLastOrdersResponse>>);

  @override
  _i11.Future<List<_i20.TopLastOrdersResponse>> getTransactionOrdersPerDate(
          _i19.DashboardDataParameter? dashboardParameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionOrdersPerDate,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<List<_i20.TopLastOrdersResponse>>.value(
            <_i20.TopLastOrdersResponse>[]),
        returnValueForMissingStub:
            _i11.Future<List<_i20.TopLastOrdersResponse>>.value(
                <_i20.TopLastOrdersResponse>[]),
      ) as _i11.Future<List<_i20.TopLastOrdersResponse>>);

  @override
  _i11.Future<List<_i20.TopLastOrdersResponse>> getTransactionOrdersPerMonth(
          [_i19.DashboardDataParameter? dashboardParameter]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionOrdersPerMonth,
          [dashboardParameter],
        ),
        returnValue: _i11.Future<List<_i20.TopLastOrdersResponse>>.value(
            <_i20.TopLastOrdersResponse>[]),
        returnValueForMissingStub:
            _i11.Future<List<_i20.TopLastOrdersResponse>>.value(
                <_i20.TopLastOrdersResponse>[]),
      ) as _i11.Future<List<_i20.TopLastOrdersResponse>>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i9.Dio {
  @override
  _i9.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_7(
          this,
          Invocation.getter(#options),
        ),
        returnValueForMissingStub: _FakeBaseOptions_7(
          this,
          Invocation.getter(#options),
        ),
      ) as _i9.BaseOptions);

  @override
  set options(_i9.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(
          #options,
          _options,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_8(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
        returnValueForMissingStub: _FakeHttpClientAdapter_8(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i9.HttpClientAdapter);

  @override
  set httpClientAdapter(_i9.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(
          #httpClientAdapter,
          _httpClientAdapter,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_9(
          this,
          Invocation.getter(#transformer),
        ),
        returnValueForMissingStub: _FakeTransformer_9(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i9.Transformer);

  @override
  set transformer(_i9.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(
          #transformer,
          _transformer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_10(
          this,
          Invocation.getter(#interceptors),
        ),
        returnValueForMissingStub: _FakeInterceptors_10(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i9.Interceptors);

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<_i9.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i9.Options? options,
    _i9.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i11.Future<_i9.Response<T>>);

  @override
  _i11.Future<_i9.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i9.Options? options,
    _i9.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i11.Future<_i9.Response<T>>);

  @override
  _i11.Future<_i9.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i9.Options? options,
    _i9.CancelToken? cancelToken,
    _i9.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i11.Future<_i9.Response<T>>);

  @override
  _i11.Future<_i9.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i9.Options? options,
    _i9.CancelToken? cancelToken,
    _i9.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i11.Future<_i9.Response<T>>);

  @override
  _i11.Future<_i9.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i9.Options? options,
    _i9.CancelToken? cancelToken,
    _i9.ProgressCallback? onSendProgress,
    _i9.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i11.Future<_i9.Response<T>>);

  @override
  _i11.Future<_i9.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i9.Options? options,
    _i9.CancelToken? cancelToken,
    _i9.ProgressCallback? onSendProgress,
    _i9.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i11.Future<_i9.Response<T>>);

  @override
  _i11.Future<_i9.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i9.Options? options,
    _i9.CancelToken? cancelToken,
    _i9.ProgressCallback? onSendProgress,
    _i9.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i11.Future<_i9.Response<T>>);

  @override
  _i11.Future<_i9.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i9.Options? options,
    _i9.CancelToken? cancelToken,
    _i9.ProgressCallback? onSendProgress,
    _i9.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i11.Future<_i9.Response<T>>);

  @override
  _i11.Future<_i9.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i9.Options? options,
    _i9.CancelToken? cancelToken,
    _i9.ProgressCallback? onSendProgress,
    _i9.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i11.Future<_i9.Response<T>>);

  @override
  _i11.Future<_i9.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i9.Options? options,
    _i9.CancelToken? cancelToken,
    _i9.ProgressCallback? onSendProgress,
    _i9.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i11.Future<_i9.Response<T>>);

  @override
  _i11.Future<_i9.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i9.Options? options,
    _i9.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i11.Future<_i9.Response<T>>);

  @override
  _i11.Future<_i9.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i9.Options? options,
    _i9.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i11.Future<_i9.Response<T>>);

  @override
  _i11.Future<_i9.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i9.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i9.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    Object? data,
    _i9.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            urlPath,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i11.Future<_i9.Response<dynamic>>.value(_FakeResponse_11<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<dynamic>>.value(_FakeResponse_11<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i11.Future<_i9.Response<dynamic>>);

  @override
  _i11.Future<_i9.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i9.ProgressCallback? onReceiveProgress,
    _i9.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    Object? data,
    _i9.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [
            uri,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i11.Future<_i9.Response<dynamic>>.value(_FakeResponse_11<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<dynamic>>.value(_FakeResponse_11<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i11.Future<_i9.Response<dynamic>>);

  @override
  _i11.Future<_i9.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i9.CancelToken? cancelToken,
    _i9.Options? options,
    _i9.ProgressCallback? onSendProgress,
    _i9.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #request,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #request,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i11.Future<_i9.Response<T>>);

  @override
  _i11.Future<_i9.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i9.CancelToken? cancelToken,
    _i9.Options? options,
    _i9.ProgressCallback? onSendProgress,
    _i9.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i11.Future<_i9.Response<T>>);

  @override
  _i11.Future<_i9.Response<T>> fetch<T>(_i9.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [requestOptions],
        ),
        returnValue: _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.Response<T>>.value(_FakeResponse_11<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
      ) as _i11.Future<_i9.Response<T>>);
}
